Updates

diff --git a/0x0C-web_server/3-redirection b/0x0C-web_server/3-redirection
--- a/0x0C-web_server/3-redirection
+++ b/0x0C-web_server/3-redirection
@@ -1,17 +1,45 @@
 #!/usr/bin/env bash
 #Configure your Nginx server so that /redirect_me is redirecting to another page
 
-apt-get update
-apt-get install -y nginx
+# Install nginx
+apt-get -y update
+apt-get -y install nginx
 
-# Create default page
-echo "Holberton School" > /var/www/html/index.html
+# Start nginx
+if [[ ! $(pgrep nginx) ]]; then
+    service nginx start
+fi
 
-# Configurate server
 ufw allow 'Nginx HTTP'
 
-# Add redirection
-new_site="https://github.com/EstephaniaCalvoC/"
-sed -i "/listen 80 default_server/a rewrite ^/redirect_me $new_site permanent;" /etc/nginx/sites-available/default
+chown -R "$USER":"$USER" /var/www/html
+chmod -R 755 /var/www
+
+root_dir=$(grep "root" /etc/nginx/sites-available/default | cut -d " " -f 2 | tr -d ";" | head -1)
+
+if [[ ! -d $root_dir ]]; then
+    sudo mkdir -p "$root_dir"
+fi
+
+echo "Hello World!" > "$root_dir"/index.html
+
+response=$(curl -s http://localhost)
+if [[ $response == "Hello World!" ]]; then
+  echo "Nginx installation and configuration successful!"
+else
+  echo "Nginx installation or configuration failed."
+  exit 1
+fi
+
+sudo sed -i "/listen 80 default_server;/a rewrite ^/redirect_me https://linkedin.com/in/achrafelkhnissi/ permanent;" /etc/nginx/sites-available/default
+
+if nginx -t | grep "successful"; then
+  echo "Nginx configuration failed."
+  exit 1
+fi
+
+nginx -s reload
 
 service nginx restart
+
+exit 0
